---
engines:
  duplication:
    enabled: true
    config:
      languages:
        javascript: 
          filters:
            - "(CallExpression callee (Identifier invariant) ___)"
ratings:
  paths:
  - "**.js"
  - "**.jsx"
exclude_paths:
- node_modules/**/*
